### ISSUE TITLE
"Something went wrong" message.

### ISSUE THREAD

**Issue by gety9** [leafac/kill-the-newsletter#106]
Before when i entered .xml url (ex: https://kill-the-newsletter.com/feeds/abc123.xml) in browser i could see feed entries, but now it says

```
Something went wrong.
Please report this issue to kill-the-newsletter@leafac.com.
```

It seems to know that feed exists, because if i enter wrong .xml url it says

```
Not found.
If you expected to see the web version of a newsletter entry, you may be interested in the answer to the question “Why are old entries disappearing?”.
```

**Comment by ggteixeira** [comment]
Same here

**Comment by mbanerjeepalmer** [comment]
Leandro is probably very aware already, but for the avoidance of doubt, the response is a 500 and no further information.

**Comment by leafac** [comment]
Hi y’all,

Thanks for reaching out. We’re back online.

The issue was that we had ran out of disk space, and the solution was to upgrade the server. So this is a great time to support Kill the Newsletter! 🤗

[Patreon](https://patreon.com/leafac) · [PayPal](https://paypal.me/LeandroFacchinettiEU) · [GitHub Sponsors](https://github.com/sponsors/leafac)
