### ISSUE TITLE
Upgrading 1.0.1 to 2.x

### ISSUE THREAD

**Issue by Daniel15** [leafac/kill-the-newsletter#109]
Is there any documentation on how to upgrade from 1.0.1 to 2.x? None of [the releases](https://github.com/leafac/kill-the-newsletter/releases) have release notes, and none of the commits in the repo have a commit message, so it's very hard to see what's changed and how to adapt my current installation.

**Comment by Daniel15** [comment]
Never mind - I just saw the CHANGLOG.md file in the repo. It would be useful to include these notes on the releases page too, as that's where I usually look for changelogs.

**Comment by leafac** [comment]
Hi @Daniel15,

Thanks for reaching out. It’s true that many projects add release notes in GitHub releases, so people (including me) tend to look there first. It’s also true that authoring a `CHANGELOG.md` file is more convenient, because it sits right there in the repository. And I didn’t find a way to conveniently extract entries from `CHANGELOG.md` into the GitHub release, and I didn’t want to do it by hand every time. So that’s how we ended up here.

If you know of an utility that addresses this, please let me know.

In any case, I’m happy that you already figured it out and that you’re self-hosting Kill the Newsletter! 🤗
