### ISSUE TITLE
Certificates not renewing

### ISSUE THREAD

**Issue by ajatoledo** [leafac/kill-the-newsletter#52]
Followed the deployment steps for KTN outlined in the materials on the github page and watched the walkthrough video for setting up no problem. KTN ran for 3 months, but then the https certificate expired and I am unable to renew it. Followed the steps in the materials provided, but it is not working.

**Comment by leafac** [comment]
Thanks for using **Kill the Newsletter!** and for reaching out. I’m sorry you’re running into this issue.

The certificate is handled by [@small-tech/auto-encrypt](https://github.com/small-tech/auto-encrypt). It should handle everything automatically, and has worked on https://kill-the-newsletter.com for a while now. I know this is going to sound silly but, have you tried restarting the service? If there’s something preventing @small-tech/auto-encrypt from renewing a certificate, restarting might help, because @small-tech/auto-encrypt checks the certificates on startup.

Other than that, I suppose I’d need more information about your deployment, because I don’t know what could be going wrong…

Let me know how it goes.

**Comment by ajatoledo** [comment]
Sorry for my delay in responding. I determined the issue was on my end, specifically my firewall settings--I limited access to my Kill the Newsletter instance to my IP address. As a result, certificate renewal could not complete successfully. You can close this issue. 

Thanks for all the great work!

**Comment by leafac** [comment]
I’m glad you figured it out.
