### ISSUE TITLE
Emails disappear after a while

### ISSUE THREAD

**Issue by ufo512** [leafac/kill-the-newsletter#59]
Hi, is there some limit on the amount of emails that can be stored under an email address? I’ve seen that they disappear after a while. What are the inbox rules or limits? Do emails in the xml file disappear after some set amount of time?

Also is there a way to extend the limit or remove it if I were to host it my own server?

**Comment by leafac** [comment]
Hi @ufo512,

Thanks for reaching out.

We remove old entries to keep Atom feeds under 500kB, because some feed readers refuse to process files bigger than that. There’s no time limit, only a size limit.

If you’re hosting Kill the Newsletter! on your own server, you can change this limit by changing [this line](https://github.com/leafac/kill-the-newsletter/blob/8b8d524b8e4b592525460a756dd5e0f582beb429/source/index.ts#L472). Unfortunately this means you’ll have to compile Kill the Newsletter! yourself, instead of using the binary we provide. That’s relatively straightforward to do and I can help if you get stuck. Perhaps in future I’ll make this easier to tweak.

You may increase the limit if you want, but I don’t recommend you remove it altogether. At some point the feed may become too large and even if your Atom feed accepts it, things may get slow.

Best.
