### ISSUE TITLE
Feature Request: Support for attachments 

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [leafac/kill-the-newsletter#66]
It appears that current implementation kill the newsletter ignores attachments on the email. It would be great if attachments could be included in the RSS News as a hyperlink.

It might be something you'd have to configure from the server side, like if you don't want your kill-the-newsletter.com hosted version to get filled up with attachmenta.

**Comment by leafac** [comment]
Hmmm 🤔

It sounds like a good idea in principle. Of course, as you mentioned, there are costs associated with this, both in terms of storage but mainly in terms of bandwidth. But it’s worth a try…

How common of an issue is it for you? Do you subscribe to many newsletters that include attachments? I find that most often they host files on their website and link from the email—even with things like images, fonts, and so forth…

**Comment by pato7** [comment]
I have one newsletter that sends PDF as an attachment, so this would be very useful in this case.

**Comment by rcarsey1** [comment]
I second this request.  Of course, RSS supports attachments (enclosures) with the <enclosure> tags inside every item.  In my use case, about 20% of emails have a PDF attached, otherwise, I would have deployed this in my environment.   I suppose for self-hosting, its a non-issue.. space is cheap.  For hosting, I could see this as a pay feature.  Additionally, there could be a setting to purge attachments/enclosures after a certain number of days.

**Comment by leafac** [comment]
Hi y’all,

I added support for attachments in version 2.0.5. They are included in the feed entries as a `<link rel="enclosure" .../>`.

Enjoy.
