### ISSUE TITLE
Feature Request: Prefetch images

### ISSUE THREAD

**Issue by mrnoname1000** [leafac/kill-the-newsletter#69]
Oftentimes marketing emails contain images with extra tracking bits in their URLs. Some email clients give the option to hide images unless prompted by the user but no RSS reader I'm aware of offers a similar feature. This leads to easy tracking of the readers and the times they decide to read.

Kill the Newsletter could mitigate this by replacing the src tags with ones that point to its own server and either prefetching them or acting as a proxy. Not sure how viable prefetching would be, as images need to be stored somewhere and usually have different URLs for different subscribers (though the content may be the same). Are old emails culled after a certain point?

**Comment by leafac** [comment]
Good point.

I suppose that proxying wouldn’t help much. As you pointed out, trackers will generate different URLs for each recipient of the newsletter, so the only thing that a proxy would conceal is the IP address of the user.

Perhaps we could download images and serve them ourselves. That’s what I think most email clients do.

But I’m reticent to do it because:

1. It would be interfering with the contents of the newsletter, which we try to avoid.

2. It would increase the storage/transfer costs for me.

> Are old emails culled after a certain point?

Yes, we remove old emails to keep the RSS feed size below a certain threshold, because some RSS feed readers don’t like big files.

**Comment by leafac** [comment]
I decided to close this issue for now. I think that Kill the Newsletter! shouldn’t modify the contents sent by the publisher, and perhaps the feed reader would be a better place to implement the feature you’re asking for.
