### ISSUE TITLE
Still does not work on ARM?

### ISSUE THREAD

**Issue by deepsu16** [leafac/kill-the-newsletter#85]
#55 says that ARM support is coming soon... That was a year ago. Is it still going to happen or has this project been abandoned?

**Comment by toelke** [comment]
I have a Dockerfile for an earlier version [here](https://github.com/toelke/kill-the-newsletter/blob/docker-build/Dockerfile) which can produce an arm64 image.

**Comment by leafac** [comment]
Hi @deepsu16,

Thanks for reaching out.

Unfortunately I worked on this for a while and concluded that there isn’t a straightforward way to create an ARM binary using GitHub Actions. (It’s possible, but it requires jumping through some hoops.)

In the interest of keeping things simple so that I can maintain them, I decided to not provide ARM binaries for now.

That said, Kill the Newsletter! should work in ARM just fine—it’s a matter of building it from source. There are pointers in the README for you to accomplish that.

Best.
