### ISSUE TITLE
How to offset timestamp in rendered feeds?

### ISSUE THREAD

**Issue by mwildx** [leafac/kill-the-newsletter#87]
I'm self hosting this using the v1.0.1 binary, minus the reverse proxy (per https://github.com/leafac/kill-the-newsletter/issues/53#issuecomment-1015383391). Everything works great, except that the timestamps for feed items are all shown as UTC/GMT, which causes them to sort and display incorrectly in my feed reader as a result.

 Is there a way to offset the item timestamps in the rendered feeds so they show the correct local time instead of UTC?

Thanks for making such a handy app!

**Comment by ajatoledo** [comment]
Follow-up: My timestamp issue is unrelated to the original comment. When I set my server TZ to `America/Detroit` the KTN feeds created feed timestamps that were UTC +5, which made my feed items appear to use UTC due to how my reader (FreshRSS) parsed the feed. Fix: update server TZ to UTC and add `export TZ=America/Detroit` to my user exports.

**Comment by leafac** [comment]
Hi @mwildx,

As far as I understand Kill the Newsletter! is doing the right thing by reporting the time in which it received the email in UTC, and it’s up to the feed reader to convert it to your timezone and sort it along with your other feeds.

With that, I’m closing the issue, but if you think there’s something that should be done on our side, please let me know.
