### ISSUE TITLE
Substack rejecting KTN adresses?

### ISSUE THREAD

**Issue by drikkes** [leafac/kill-the-newsletter#90]
I tried it today with 2 different Substack Newsletters and 2 different KTN Inboxes in 2 differnt browsers. The result is always:

> Please enter a valid email
> We were unable to validate your email domain

Anyone else have problems like this?

**Comment by candideu** [comment]
Hmm.... I was able to subscribe to Alyssa X's Substack via Feeder. It doesn't look like you can [ban domains on Substack](https://support.substack.com/hc/en-us/articles/360059791732-How-do-I-ban-a-list-of-users-from-commenting-or-subscribing-) either...

**Comment by candideu** [comment]
Edit: Nevermind, I subscribed to her newsletter by typing the URL of the feed followed by "/feed"

**Comment by NoelDeMartin** [comment]
I am having the same problems, I contacted the creator of the newsletter and they confirmed everything looks right on their side so I think it must be something with KTN :( Other newsletters are working fine, so it must be Substack doing something.

**Comment by NoelDeMartin** [comment]
So, I contacted substack support to learn more about this, and they replied the following:

> Regarding the [@kill-the-newsletter.com](mailto:cbatiresykrukvceilzy@kill-the-newsletter.com), it looks like we're attempting to send emails to this email address, but it's being dropped by your email service provider, which is why you're not receiving the posts in your inbox.

Maybe @leafac can bring some light to this problem?

Although I have to say, I still think it's quite weird because most of my newsletters are working, except the ones hosted on substack. Furthermore, I tried sending emails manually and they are appearing in the feed so it still looks like there's something wrong with Substack. But I can't be sure :/.

In case it is useful, they shared the following url for sending test emails. But using it, just confirmed that it doesn't work:

`https://{username}.substack.com/account/email-test?email={email}` (substitute `{username}` with the newsletter name and `{}` with your KTN email address).

**Comment by drikkes** [comment]
As @candideu wrote, it's not much of a hassle, because you can subscribe to a Substack's feed directly. (But I liked the fact, that the nl owner saw the mailadress, when checking new subscribers.)

**Comment by NoelDeMartin** [comment]
@drikkes But that doesn't work for paid subscriptions, right?

**Comment by JoshuaPettus** [comment]
dumb question, but did you make sure to remove the spaces before and after when you copied the KTN email address?

I had noticed that with another service, then once I fixed it it worked.

**Comment by fncll** [comment]
Is there any update on this issue or way to help troubleshoot? It doesn't appear there is a feed in Substack to use for paid newsletters that includes paid content.

**Comment by JoshuaPettus** [comment]
Maybe as a work around you can have your newsletter delivered to your email and then have your email account forward the email to KTN?  Gmail can do this for instance.

**Comment by fncll** [comment]
Thanks. That's what I'm doing now, but it would be great to have this resolved. It feels to me like Substack is prevaricating...

**Comment by drod3763** [comment]
I came here looking to see if anyone else had this issue. I used to get substack newsletters delivered using KTN to my RSS but it looks like they stopped delivering them sometime around January of 2023. It looks like they outright banned KTN emails.

**Comment by leafac** [comment]
Hi everyone 👋

As some of you have determined, emails coming from other sources are processed by Kill the Newsletter! just fine, so the issue seems to be on Substack’s side. I haven’t reached out to them, but most likely they blocklisted Kill the Newsletter! I’m happy to read that they provide feeds themselves, so Kill the Newsletter! isn’t even needed 🤗
