### ISSUE TITLE
[Feature Request] Support separate IDs for addresses and feeds

### ISSUE THREAD

**Issue by halphalp** [leafac/kill-the-newsletter#93]
I have a collection of feeds that I'd like to share with other users, but I don't want them to be able to guess what the e-mail address is and have the ability to sign the feed up for more newsletters.

Would it be possible to add a configuration option to have a custom name for the feed while retaining a random string of characters for the e-mail address that feed viewers wouldn't be able to guess?

**Comment by EasternPA** [comment]
I went a little overboard with my isolation techniques, but here's what I do:

1. Create a new KTN inbox
2. Subscribe to it in a self-hosted FreshRSS instance
3. Use BitWarden to generate a new password without any special characters. Just upper, lower, and numbers
4. Go to duckduckgo.com/email to generate a new Duck email address using that BitWarden-generated password
5. Configure it to forward to KTN
6. You will get a warning that Duck cannot cloak your email address if you send any replies from KTN; no problem
7. Subscribe to the newsletter with the duck address.

With this setup, any trackers are removed from the email before it goes to KTN. KTN deletes the emails after a day or two, but that's fine. If I want to read a newsletter online that KTN has already deleted, most of them have a "read online" link (but that destroys my privacy). I use Brave with the Privacy Badger and Adblock Plus extensions to try to save any shards of privacy I have left.

I also wrote scripts to get free newspaper subscriptions through various libraries and used this setup for each newspaper login. Sure, I subscribe to all of their RSS feeds, but I also subscribe to almost all their newsletters. They have no idea that my Duck email address goes to KTN. The only downside is that there's only one KTN inbox for each newspaper, so all of their newsletters arrive in a bit of a mish-mosh. I could create a new duck address for EACH newsletter, but there are nearly 50 across them all.

This is also how I'm searching for a new car. I configure alerts at AutoTempest, but every car I'm considering gets its Duck address, which then forwards to an individual KTN inbox. Then, I subscribe to each alert feed in FreshRSS. I can see within minutes to hours whenever a car I might be interested in becomes available. It feels like the cars come to me instead of vice versa.

**Comment by leafac** [comment]
Hi @halphalp,

Thanks for reaching out.

In the past I had the same idea as you, but I decided against it. I don’t want to encourage sharing of Kill the Newsletter! feeds because it may be bad for newsletter publishers, who may want to know how many people they’re reaching. Kill the Newsletter! already detaches the identity of the person from the email address, and for some publishers that’s already bad enough that they blocklist Kill the Newsletter! 😬

Also, it’s easy enough for people interested in the newsletter to create their own Kill the Newsletter! feeds. So I prefer to leave it at that.

---

And @EasternPA, I loved reading about your setup. So creative! 🤗
