### ISSUE TITLE
Cant find configuration file for self-hosted

### ISSUE THREAD

**Issue by joyoner** [leafac/kill-the-newsletter#94]
I need self-hosted, and after following the video or the github doc, I can't find the configuration file deployment-example/configuration.js , I think he is a file in the historical version, which is no longer available in the latest github repository.
Which configuration file should I use if I want to use the binary from the release?

**Comment by CyberFoxar** [comment]
It's because @leafac didn't make a release for main yet.

The configuration file that is both reference in the readme and by the 1.0.1 release is available in the 1.0.1 commit at https://github.com/leafac/kill-the-newsletter/blob/58657a1688957eefcf20d58ba6efaec37bab62f0/deployment-example/configuration.js
