### ISSUE TITLE
How to change the Auto Delete Entries period

### ISSUE THREAD

**Issue by gt-sun** [leafac/kill-the-newsletter#98]
I've been running my self-host service for several months now, and recently I've been seeing entries 404, which are automatically deleted in few days. So How and where can I change the period? thanks

**Comment by leafac** [comment]
Hi @gt-sun,

Thanks for reaching out.

The deletion of old entries is not based on time, but space: we keep the feeds under a certain size limit because some feed readers don’t even support big feeds. Also to control the costs of hosting `kill-the-newsletter.com`: bandwidth and storage can get expensive ($150 on the last month 😅).

To change this on your installation, modify [this line](https://github.com/leafac/kill-the-newsletter/blob/37caf3a24bcff9d620698dafbd115feff1f0f377/source/index.mts#L782), then [build from source](https://github.com/leafac/kill-the-newsletter/blob/37caf3a24bcff9d620698dafbd115feff1f0f377/.github/workflows/main.yml#L18-L19).

Best.
